=== MurmurationsNetwork/IndexService/playground/concurrency-issues/schemas/wrong.json
{
    "$schema": "https://json-schema.org/draft-04/schema#",
    "id": "https://raw.githubusercontent.com/MurmurationsNetwork/MurmurationsServices/indexAPI/",
    "title": "Demo Schema",
    "description": "A demo schema that is to be used only for testing purposes.",
    "type": "object",
    "properties": {
        "profileUrl": {
            "$ref": "playground/concurrency-issues/fields/wrong/profileurl-v1.json"
        },
        "linkedSchemas": {
            "$ref": "playground/concurrency-issues/fields/wrong/linkedschemas-v1.json"
        },
        "name": {
            "$ref": "playground/concurrency-issues/fields/wrong/name-v1.json"
        },
        "url": {
            "$ref": "playground/concurrency-issues/fields/wrong/url-v1.json"
        },
        "mission": {
            "$ref": "playground/concurrency-issues/fields/wrong/mission-v1.json"
        },
        "geolocation": {
            "$ref": "playground/concurrency-issues/fields/wrong/geolocation-v1.json"
        },
        "keywords": {
            "$ref": "playground/concurrency-issues/fields/wrong/keywords-v1.json"
        }
    },
    "required": [
        "profileUrl",
        "linkedSchemas",
        "name",
        "url"
    ],
    "metadata": {
        "owner": {
            "name": "Murmurations Network",
            "url": "https://murmurations.network"
        }
    }
}

=== MurmurationsNetwork/IndexService/playground/concurrency-issues/document.json
{
    "profileUrl":"https://ic3.dev/test1.json",
    "linkedSchemas":[
       "demo-v1"
    ],
    "name":"IC3 Dev",
    "url":"https://ic3.dev",
    "mission":"We make stuff...",
    "geolocation":{
       "lat": 12.121212,
       "lon": 13.131313
    },
    "keywords":[
       "open-source",
       "beer"
    ]
 }

=== MurmurationsNetwork/IndexService/playground/gojsonschema/document.json
{
    "profileUrl":"https://ic3.dev/test1.json",
    "linkedSchemas":[
       "demo-v1"
    ],
    "name":"IC3 Dev",
    "url":"https://ic3.dev",
    "mission":"We make stuff...",
    "geolocation":{
       "latitude": 12.121212,
       "longitude": 13.131313
    },
    "keywords":[
       "open-source",
       "beer"
    ]
 }
